scrape_task:
  description: >
    Conduct a thorough scrape of a website with from a given URL using
    provided tools and return all scraped content in a neat and readable manner.
  expected_output: >
    All scraped content from the website in a readable structure
  agent: scraper


